### ISSUE TITLE
Contribute to `explosiv`?

### ISSUE THREAD

**Issue by vixalien** [fs-c/dhow#3]
Hey there!! I've created a fork of `dhow` called [`explosiv`](https://github.com/vixalien/explosiv). It has recently started to gain traction (about 50 stars) and I would appreciate if you would want to discuss contribution of your changes to `dhow` to `explosiv` or even merge them??

**Comment by signalwerk** [comment]
@vixalien I feel very uncomfortable when I see what you did with your "fork". I know we are all cool and open and share our code, but your behavior feels not like you have a focus on the community.

1. You never tried to contribute back to dhow
2. you took the project to your repo without the fork function to see it's origin
3. you took already key-concepts of @fs-c 
4. you now ask to "discuss" some contributions. 

Sir with all respect; me as a bystander already feel uncomfortable I can't imagine how @fs-c must feel. 
His efforts to contribute back to dhow earns my deepest respect and how politely and with a lot of care he treated the maintainer, the existing users and the project is a great example how opensource should work. even if the current maintainer @kartiknair was not responding he kept his horses and mad what was to do in such a situation.

I wish you all the best with maintaining a sustainable community and hope your project (great name by the way) will be inclusive in the future.

**Comment by vixalien** [comment]
oh yeah right. this was mu first open source so you must imagine I felt a little bit greedy. and I also felt explosiv had evolved something of its own that @kartiknair would not merge to upstream. as for the fork tag, that's because I cloned and re-uploaded to github I don't really know what happened (if there's a way to fix this please tell me.)

And thanks by the way, if there's any steps you would like me to take, I'll do them right away.

**Comment by vixalien** [comment]
BTW initially I wanted to scramble the explosiv project because I'm running out of time to contribute and update dependencies and so wanted to merge explosiv with this fork of dhow because i thought it was necessary however I now understand that what i did was wrong and would like to apologize sincerely.

**Comment by fs-c** [comment]
Thanks @signalwerk for the kind words, it means a lot to me.

@vixalien I am not currently interested in contributing to your fork, especially since you mention that you will not have the time to maintain it.  (And your improvements over upstream seem marginal at best, to be honest.)
