### ISSUE TITLE
`dangerouslySetInnerHTML` vs. `html`

### ISSUE THREAD

**Issue by signalwerk** [fs-c/dhow#6]
@fs-c 
When I took over some components from a regular frontend react project, I had a `dangerouslySetInnerHTML` in my component. That didn't work out of the box for dhow and I was searching for a solution. But of course you already had the solution in your code;

https://github.com/fs-c/dhow/blob/rewrite/src/lib/jsx-runtime.ts#L74-L78

What do you think? Wouldn't it be more «natural» for react developer to have the same `dangerouslySetInnerHTML` attribute as in other projects? I'm not thrilled about the naming in React, but I have to say the word «dangerous» in my code-base makes me usually think twice if I really need it. Plus, I think the explanation in the [react docu](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) also makes it simple for people to find it and apply the same technic with dhow.

Let me know what you think.

**Comment by fs-c** [comment]
I considered naming the attribute analogously to react when I added support for it. But I don't think it's a very good name here, since what makes it dangerous in the context of react doesn't really apply. (You can't use it to inject user-provided content into the HTML.)

But I wouldn't be averse to adding `dangerouslySetInnerHTML` as an alias, please feel free to submit a PR.

**Comment by signalwerk** [comment]
I see the danger for `dangerouslySetInnerHTML` primarly in the ability to have the option to break the DOM. You can't generate illegal HTML-Tags if you're in «normal» react but if you go `dangerouslySetInnerHTML` you have to be careful... I see the same danger for dhow. As soon as you inline HTML you're responsible to check before where the data comes from. and since dhow can get the date from all kind of sorces I would see the same logic apply here.  
But in general I was more not finding it, because I'm a react-user and was trying what I already knew. So I didn't know the specifics of dhow.

**Comment by fs-c** [comment]
I see your point. Really, what's important here is that following the React API closely is a Good Thing as far as DX is concerned, and that should naturally be a priority.

Added it as an alias.

**Comment by signalwerk** [comment]
☺️ thanks a lot for your patch! awesome!
